using System;
using System.Collections.Generic;
using System.Text;

namespace JCGodSwornConfigurator
{
    public class LocManager
    {
        //Names from units in skirmish and campaign (not placeholders or unfinished units)
        public static readonly List<string> legalUnitNames = new List<string> {
                "Herbalist",
                "Leshi",
                "Marauder",
                "Mercenary",
                "Pukis",
                "Raider",
                "Ranger",
                "ShadowWolf",
                "Shadows",
                "Skirmisher",
                "Skybull",
                "Spigana Naave",
                "Spigana",
                "Stardaughter - Indraja",
                "Stardaughter - Lunar",
                "Stardaughter - Solar",
                "TradeCart",
                "Tribesman",
                "Warrior",
                "Werewolf",
                "Witch",
                "WolfWarrior",
                "Worshipper_Baltic Female",
                "Worshipper_Baltic Male",
                "BearSlayer",
                "GabjasFireSpirit",
                "IronWolf",
                "RaiderFoot",
                "Tatar Horseman",
                "Usigns",
                "Varangian",
                "Bishop_Meinhard",
                "Avenging Angel",
                "Blackknight",
                "Cannon",
                "Catapult",
                "Cherub - Eagle",
                "Cherub - Lion",
                "Cherub - Ox",
                "Footman",
                "FootKnight",
                "FootPaladin",
                "Knight",
                "MG42Knight",
                "Paladin",
                "Sergeant",
                "LongbowMan",
                "Marksman",
                "Militant",
                "Militia",
                "Nurse",
                "Rogue",
                "Squire",
                "Tracker",
                "Tracker_Unmounted",
                "Trebuchet",
                "Worshipper_Order Female",
                "Worshipper_Order Male",
                "Zealot",
                "Meinhard",
                "Indraja",
                "Sword Brother Master",
                "Bear",
                "Calf",
                "Cow",
                "Sky Calf",
                "SkyCow",
                "Wolf"
            };
    }
}
